// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered resume/CV analysis for employers.
 *
 * - aiResumeAnalysis - A function that handles the resume analysis process.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { AIResumeAnalysisInputSchema, AIResumeAnalysisOutputSchema, type AIResumeAnalysisInput, type AIResumeAnalysisOutput } from '@/lib/schemas';

export async function aiResumeAnalysis(input: AIResumeAnalysisInput): Promise<AIResumeAnalysisOutput> {
  return aiResumeAnalysisFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiResumeAnalysisPrompt',
  input: {schema: AIResumeAnalysisInputSchema},
  output: {schema: AIResumeAnalysisOutputSchema},
  prompt: `You are an expert recruiter specializing in candidate evaluation.

You will use this information to evaluate the candidate, and rank them based on their resume.

Job Description: {{{jobDescription}}}

Resume: {{media url=resumeDataUri}}

Candidate Ranking (1-100): Rank the candidate from 1 to 100, with 100 being the best candidate.
Candidate Summary: Summarize the candidate's resume.
Key Skills Match: List the key skills that match the job description.
Areas for Improvement: List areas for improvement for the candidate.`,
});

const aiResumeAnalysisFlow = ai.defineFlow(
  {
    name: 'aiResumeAnalysisFlow',
    inputSchema: AIResumeAnalysisInputSchema,
    outputSchema: AIResumeAnalysisOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
